module TopLevelCommSystem(
	/* Inputs */ clk, SW, KEY, LEDR);
	
	input clk;
	input [7:0] SW;
	input [0:0] KEY;
	output [7:0] LEDR;
	
	// Instantiate the Nios II system module generated by the Qsys tool:
	nios_sys NiosII (
		.clk_clk(clk),
		.reset_reset_n(KEY),
		.switches_external_connection_export(SW),
		.leds_external_connection_export(LEDR));

		
endmodule
